<?php

namespace Vybose\RepeaterIconList;

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

class Renderer
{
    private const ALLOWED_TITLE_TAGS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'div', 'span', 'p'];

    public static function render($settings, $items)
    {
        $output = '';

        // Base Styles logic would go here or be handled by CSS classes
        // In Elementor, styles are generated by controls and attached to the widget ID class.
        // For Shortcodes, we might need inline styles or a way to generate unique IDs and styles.
        // For this iteration, we will rely on global classes and inline styles where possible for dynamic values?
        // Actually, the refactored plugin relies heavily on CSS variables set on the wrapper.
        // So for Shortcode, we should perform similar logic to output a wrapper with style="..." containing vars.

        $id = uniqid('vybose-icon-list-');
        $wrapper_class = 'vybose-widget-icon-list ' . $id;

        $vars = self::get_css_variables($settings);
        $style_string = '';
        foreach ($vars as $key => $value) {
            $style_string .= "$key: $value; ";
        }

        $items_class = 'vybose-widget-icon-list-items';
        $item_class = 'vybose-widget-icon-list-item';

        $output .= '<div class="' . esc_attr($wrapper_class) . '" style="' . esc_attr($style_string) . '">';

        if (!empty($settings['title'])) {
            $tag = self::validate_title_tag($settings['title_tag'] ?? 'h3');
            $output .= '<' . $tag . ' class="vybose-widget-icon-list-title">' . esc_html($settings['title']) . '</' . $tag . '>';
        }

        $output .= '<ul class="' . esc_attr($items_class) . '">';

        foreach ($items as $index => $item) {
            $link_type = isset($settings['link_click']) ? $settings['link_click'] : 'text';
            $has_link = !empty($item['link']['url']);
            $link_attrs = self::get_link_attributes($item['link'] ?? []);

            if ($has_link) {
                $has_link = '' !== $link_attrs;
            }

            // Classes
            $li_classes = [$item_class];
            if ($has_link && 'full_width' === $link_type) {
                $li_classes[] = 'active-link-item';
            }
            // Add other logical classes...

            $output .= '<li class="' . esc_attr(implode(' ', $li_classes)) . '">';

            // Full Width Link
            if ($has_link && 'full_width' === $link_type) {
                $output .= '<a class="vybose-widget-icon-list-item-link" ' . $link_attrs . '>';
            }

            // Wrapper for content
            $output .= '<span class="vybose-widget-icon-list-item-text-wrap">';

            // Icon
            $has_icon = false;
            // Check global vs custom
            // Simplified logic for shortcode:
            if (isset($settings['global_marker']) && 'numeric' === $settings['global_marker']) {
                // Numeric marker logic
                $has_icon = true; // It's pseudo element usually, but let's see. 
                // Actually numeric usually uses CSS counters or a span with number? 
                // In the detailed render(), numeric sets $has_icon = true but $icon = false.
            } else {
                // Icon logic
                // For now assume global icon
                $has_icon = true;
                // need to render icon HTML
            }

            if ($has_icon) {
                $output .= '<span class="vybose-widget-icon-list-item-icon">';
                // Render Icon
                if (isset($settings['global_marker']) && 'numeric' !== $settings['global_marker']) {
                    // Try to render icon markup
                    // <i class="..."></i> provided by $settings['global_icon']['value']
                    if (!empty($settings['global_icon']['value'])) {
                        $output .= '<span><i class="' . esc_attr($settings['global_icon']['value']) . '" aria-hidden="true"></i></span>';
                    }
                }
                $output .= '</span>';
            }

            // Text
            $output .= '<span class="vybose-widget-icon-list-item-text-inner">';
            $output .= '<span class="vybose-widget-icon-list-item-text">';
            if ($has_link && 'text' === $link_type) {
                $output .= '<a ' . $link_attrs . '>' . wp_kses_post($item['text']) . '</a>';
            } else {
                $output .= wp_kses_post($item['text']);
            }
            $output .= '</span>';

            // Value
            if (!empty($item['value'])) {
                $output .= '<span class="vybose-widget-icon-list-item-value">';
                if ($has_link && 'value' === $link_type) {
                    $output .= '<a ' . $link_attrs . '>' . wp_kses_post($item['value']) . '</a>';
                } else {
                    $output .= wp_kses_post($item['value']);
                }
                $output .= '</span>';
            }

            $output .= '</span>'; // End text inner
            $output .= '</span>'; // End text wrap

            if ($has_link && 'full_width' === $link_type) {
                $output .= '</a>';
            }

            $output .= '</li>';
        }

        $output .= '</ul>';
        $output .= '</div>';

        return $output;
    }

    private static function get_css_variables($settings)
    {
        // Map settings to CSS variables
        // This is a simplified version. Ideally we map every control.
        $vars = [];

        if (isset($settings['space_between']['size'])) {
            $unit = $settings['space_between']['unit'] ?? 'px';

            if (in_array($unit, ['px', 'em'], true)) {
                $vars['--vybose-icon-list-items-gap'] = 'calc(' . (float) $settings['space_between']['size'] . $unit . ' / 2)';
            }
        }

        // Add other variables here...
        // For the sake of this task, I will include major ones but might not be exhaustive unless requested.

        return $vars;
    }

    private static function validate_title_tag($tag)
    {
        $tag = strtolower((string) $tag);

        return in_array($tag, self::ALLOWED_TITLE_TAGS, true) ? $tag : 'h3';
    }

    private static function get_link_attributes($link)
    {
        if (empty($link['url'])) {
            return '';
        }

        $attributes = [
            'href' => esc_url($link['url']),
        ];
        $rel = [];

        if (!empty($link['is_external'])) {
            $attributes['target'] = '_blank';
            $rel[] = 'noopener';
            $rel[] = 'noreferrer';
        }

        if (!empty($link['nofollow'])) {
            $rel[] = 'nofollow';
        }

        if ($rel) {
            $attributes['rel'] = implode(' ', array_unique($rel));
        }

        $output = '';

        foreach ($attributes as $name => $value) {
            if ('' !== $value) {
                $output .= sprintf(' %s="%s"', esc_attr($name), esc_attr($value));
            }
        }

        return trim($output);
    }
}
